export const builderData = {
  "skills": [
      "Content Marketing",
      "Paid Ads",
      "Social Media Marketing",
      "Graphic Designer",
      "Content Writing",
      "Web Developer",
      "2D Illustration",
      "Affiliate Marketing",
      "Business Strategy",
      "Content Strategy",
      "Data Analysis",
      "Email Marketing",
      "Creative Strategy",
      "3D Animation",
      "Facebook Ads",
      "Google Ads",
      "Graphic Design",
      "Influencer Marketing",
      "PPC Marketing",
      "SEO Expert",
      "UI/UX",
      "User Generated Content",
      "Video Editing",
      "Frontend Developer",
      "Frontend",
      "Backend",
      "MERN Developer",
      "Full Stack Developer",
      "NextJs",
      "NextJs Developer",
      "Web Dev",
      "MongoDB",
      "Express.js",
      "ReactJS",
      "React Developer",
      "ReactJs Developer",
      "Node.js",
      "NodeJs Developer",
      "Bootstrap",
      "Material-UI",
      "Database Design",
      "SQL",
      "NOSQL",
      "Computer Science",
      "HTML",
      "CSS",
      "Javascript",
      "Redux",
      "Context API",
      "Code Review",
      "Unit Test",
      "Bugs",
      "Industry Trends",
      "Restful APIs",
      "Web Security",
      "JWT",
      "OAuth",
      "AWS",
      "Firebase",
      "Backend Development",
      "React Query",
      "SWR",
      "Chakra UI",
      "Problem Solving",
      "LLM",
      "Python",
      "Django",
      "Flask",
      "Java",
      "AngularJs",
      "Socket.io",
      "Websockets",
      "OpenAI",
      "Deepseek",
      "Linkedin",
      "Instagram",
      "Twitter",
      "Typescript",
      "Git",
      "Chrome Extension",
      "Testing & Debugging",
      "Zustand",
      "Digital Ocean",
      "Hostinger",
      "AWS S3",
      "PHP",
      "Laravel",
      "Vue.js",
      "PostgreSQL",
      "Authentication",
      "Gitlab",
      "Bitbucket",
      "Jest",
      "React Testing Library",
      "Framer Motion",
      "Webflow Developer",
      "Wix Developer",
      "2D Animation",
      "2D Animator",
      "2D Illustrator",
      "3D Animator",
      "3D Illustration",
      "3D Illustrator",
      "A/B Testing",
      "Account Management",
      "Actor",
      "Advertising",
      "Advisor",
      "AI Artist",
      "Amazon Marketer",
      "Angel Investor",
      "Animation",
      "Apollo Expert",
      "AR Developer",
      "AR Expert",
      "Art Direction",
      "Blogger",
      "Blogging",
      "Brand Management",
      "Brand Solutions",
      "Branding Strategy",
      "BTL Expert",
      "Business Development",
      "Canva Expert",
      "Chatbot Marketing",
      "Client Management",
      "Communications & PR",
      "Content Creation",
      "Content Creator",
      "Conversion Revenue Optimisation (CRO)",
      "Copywriting",
      "Corporate Communications",
      "Creator",
      "Customer Service",
      "Customer Success",
      "DALL-E Expert",
      "Dancer",
      "Demand Generation",
      "Design",
      "Designer",
      "Digital Marketer",
      "Digital Marketing",
      "Direct Mail Marketing",
      "Display Advertising",
      "Doodle Artist",
      "Due Diligence",
      "E-commerce Specialist",
      "Ecommerce Growth",
      "Educator",
      "Email Marketer",
      "Emcee",
      "Engineer",
      "Entrepreneur",
      "Event Marketer",
      "Event Marketing",
      "Financial Analysis",
      "Financial Management",
      "Founder",
      "Fundraising",
      "Gaming",
      "Ghostwriter",
      "Ghostwriting",
      "Google Analytics Specialist",
      "Google Premier Partner",
      "Grant Writing",
      "Growth Hacker",
      "Growth Hacking",
      "Growth Marketer",
      "Hubspot Certified",
      "Hubspot Expert",
      "Illustration",
      "Influencer",
      "Instagrammer",
      "Interaction Design",
      "Investor",
      "Lead Generation",
      "Leadership",
      "Logo Design",
      "Market Research",
      "Marketing",
      "Media Personality",
      "Media Planner",
      "Media Strategy",
      "Meta Blueprint Certified",
      "MidJourney Expert",
      "Mixpanel Specialist",
      "Mobile Marketing",
      "Motion Graphics",
      "Native Advertising",
      "Packaging Design",
      "Performance Marketer",
      "Performance Marketing",
      "Pet Parent",
      "Photography",
      "Pinterest Marketing",
      "Podcast Advertising",
      "Podcaster",
      "Portfolio Management",
      "Print Design",
      "Producer",
      "Product Development",
      "Product Marketer",
      "Product Marketing",
      "Project Management",
      "Public Relations",
      "Public Relations Expert",
      "Public Speaking",
      "Retargeting",
      "Sales Expert",
      "Salesforce Expert",
      "Screenwriter",
      "SEM Expert",
      "Semrush Certified",
      "Shopify Developer",
      "Shopify Marketer",
      "Software Engineer",
      "Sports Enthusiast",
      "Sports Marketing",
      "Startup Strategy",
      "Strategic Planning",
      "Talent Management",
      "Teacher",
      "Team Management",
      "Translation",
      "Traveller",
      "TV Host",
      "Twitter / X Marketing",
      "User Experience Design (UED)",
      "User-Centered Design",
      "Venture Capital",
      "Video Creator",
      "Video Marketing",
      "Video Producer",
      "Viral Marketing",
      "Visual Design",
      "Voice Search Optimization",
      "Voiceover Artist",
      "VR Developer",
      "VR Expert",
      "Web Design",
      "Web Development",
      "Wedding Planner",
      "WhatsApp Marketing",
      "WordPress Designer",
      "WordPress Developer",
      "Writer",
      "YouTube Ads",
      "YouTube Creator",
      "Zoho Expert"
  ]
}


export const emojiMap = {
    // 💻 Software Development & Programming
    javascript: "⭐",
    typescript: "🔥",
    react: "⚛️",
    nextjs: "🚀",
    vue: "🍃",
    angular: "🅰️",
    svelte: "🔥",
    nodejs: "🌿",
    express: "⚡",
    nestjs: "🏛️",
    python: "🎯",
    django: "💻",
    flask: "🥛",
    java: "☕",
    spring: "🌱",
    kotlin: "📱",
    swift: "🍏",
    dart: "🎯",
    flutter: "🦋",
    php: "🐘",
    laravel: "🛑",
    ruby: "💎",
    rails: "🚂",
    c: "🔵",
    "c++": "📢",
    "c#": "🎸",
    go: "📢",
    rust: "🦀",
  
    // 📊 Data & Databases
    sql: "🗄️",
    mysql: "🐬",
    postgresql: "🐘",
    mongodb: "🍃",
    firebase: "🔥",
    redis: "🟥",
    cassandra: "💠",
    bigquery: "📊",
    datascience: "📊",
    analytics: "📈",
  
    // ☁️ Cloud & DevOps
    aws: "☁️",
    azure: "🔷",
    gcp: "☁️",
    docker: "🐳",
    kubernetes: "⛵",
    terraform: "🏗️",
    ansible: "🤖",
    jenkins: "🛠️",
    ci: "🔄",
    cd: "🚀",
  
    // 🌐 APIs & Web Services
    graphql: "🔮",
    restapi: "🌐",
    json: "📝",
    soap: "🛁",
  
    // 🎨 UI/UX & Frontend Development
    html: "📜",
    css: "🎨",
    tailwind: "🌊",
    bootstrap: "🅱️",
    sass: "💄",
    less: "🎭",
    figma: "🎨",
    adobe: "🖌️",
    adobexd: "🖌️",
    photoshop: "🖼️",
    illustrator: "🎨",
    ux: "👁️",
    ui: "🖥️",
    wireframing: "📝",
    prototyping: "📏",
  
    // 🧪 Testing & QA
    testing: "🧪",
    jest: "🃏",
    mocha: "☕",
    cypress: "🌲",
    selenium: "🤖",
    unittesting: "🛠️",
    automation: "🔄",
  
    // 🔒 Cybersecurity & Networking
    cybersecurity: "🔒",
    ethicalhacking: "🕵️",
    networking: "📡",
    penetrationtesting: "🛡️",
    firewall: "🚧",
  
    // AI, Machine Learning & Data Science
    ai: "💡",
    ml: "🔥",
    deeplearning: "🌀",
    tensorflow: "🦾",
    pytorch: "🔥",
    opencv: "👀",
    nlp: "🗣️",
    datavisualization: "📊",
    bigdata: "💾",
  
    // ⛓️ Blockchain & Web3
    blockchain: "⛓️",
    ethereum: "💎",
    bitcoin: "🟠",
    solidity: "🛠️",
    smartcontract: "📜",
    defi: "🏦",
    nft: "🎨",
    metaverse: "🌐",
    web3: "🔗",
  
    // ⚡ Agile & Collaboration
    agile: "⚡",
    scrum: "🏉",
    kanban: "📋",
    jira: "🐞",
    trello: "🗂️",
    asana: "📅",
    notion: "📝",
  
    // 🌎 Other Industries
    finance: "💰",
    fintech: "🏦",
    healthcare: "🏥",
    biotech: "🧬",
    edtech: "📚",
    gamedev: "🎮",
    marketing: "📢",
    seo: "🔍",
    sales: "💼",
    ecommerce: "🛒",
    logistics: "🚛",
    supplychain: "📦",
    retail: "🏬",
    customerexperience: "😊",
    graphic: '🎨',
  
    // Default
    default: "💻",
  };
  

export const colors = [
    { color: "#ffffff", name: "Pearl White" },
    { color: "#ffe7ce", name: "Apricot Cream" },
    { color: "#ffcda8", name: "Coral Blush" },
    { color: "#ffaac9", name: "Pink Raspberry" },
    { color: "#e4a5ff", name: "Lavender Mist" },
    { color: "#000000", name: "Midnight Black" },
    { color: "#ec53b0", name: "Electric flamingo" },
    { color: "#279eff", name: "Skyline blue" },
    { color: "#4d2db7", name: "Cosmic Purple" },
    { color: "#0e21a0", name: "Deep sapphire" },
];


export const textColorMapping: Record<string, string> = {
    "#ffffff": "text-black", 
    "#ffe7ce": "text-black",
    "#ffcda8": "text-black",
    "#ffaac9": "text-black",
    "#e4a5ff": "text-black",
    "#000000": "text-white",
    "#ec53b0": "text-white",
    "#279eff": "text-white",
    "#4d2db7": "text-white",
    "#0e21a0": "text-white",
  };

  export const colorMapping: Record<string, string> = {
    "#ffffff": "black", 
    "#ffe7ce": "black",
    "#ffcda8": "black",
    "#ffaac9": "black",
    "#e4a5ff": "black",
    "#000000": "white",
    "#ec53b0": "white",
    "#279eff": "white",
    "#4d2db7": "white",
    "#0e21a0": "white",
};
